Import('env')
env.Append(CPPPATH=['../3rd/tinyxml', '../3rd/hash'])
src = Glob('*.cpp')
src.remove(File('dllmain.cpp'))

objs = []

platform = env['PLATFORM']
if str(platform) == 'win32':
    build_type = env['BUILD_TYPE']
    if str(build_type) == 'dll':
        src.append(File('dllmain.cpp'))
        objs.append(env.RES('XBasic.rc'))

objs.append(env.Object(src))

Return('objs')
